language: go
sudo: false
go:
  - "1.5"
before_script:
  - go vet ./...
install:
  - go get github.com/tools/godep
  - godep restore
  - go get github.com/onsi/ginkgo/ginkgo
script:
  - make all
  - make test
deploy:
  provider: releases
  file: build/ice-clique
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    tags: true

