language: go
sudo: false
go:
  - "1.7"
install:
  - go get github.com/Masterminds/glide
  - make deps
  - go get github.com/onsi/ginkgo/ginkgo
script:
  - make all
  - make lint
  - make test
deploy:
  provider: releases
  file: ./build/clique-agent
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    tags: true

