// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/ice-stuff/clique/api"
	"github.com/ice-stuff/clique/api/registry"
)

type FakeTransferStater struct {
	TransferStateStub        func() api.TransferState
	transferStateMutex       sync.RWMutex
	transferStateArgsForCall []struct{}
	transferStateReturns     struct {
		result1 api.TransferState
	}
}

func (fake *FakeTransferStater) TransferState() api.TransferState {
	fake.transferStateMutex.Lock()
	fake.transferStateArgsForCall = append(fake.transferStateArgsForCall, struct{}{})
	fake.transferStateMutex.Unlock()
	if fake.TransferStateStub != nil {
		return fake.TransferStateStub()
	} else {
		return fake.transferStateReturns.result1
	}
}

func (fake *FakeTransferStater) TransferStateCallCount() int {
	fake.transferStateMutex.RLock()
	defer fake.transferStateMutex.RUnlock()
	return len(fake.transferStateArgsForCall)
}

func (fake *FakeTransferStater) TransferStateReturns(result1 api.TransferState) {
	fake.TransferStateStub = nil
	fake.transferStateReturns = struct {
		result1 api.TransferState
	}{result1}
}

var _ registry.TransferStater = new(FakeTransferStater)
