// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/ice-stuff/clique/api"
)

type FakeTransferCreator struct {
	CreateStub        func(api.TransferSpec)
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 api.TransferSpec
	}
}

func (fake *FakeTransferCreator) Create(arg1 api.TransferSpec) {
	fake.createMutex.Lock()
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 api.TransferSpec
	}{arg1})
	fake.createMutex.Unlock()
	if fake.CreateStub != nil {
		fake.CreateStub(arg1)
	}
}

func (fake *FakeTransferCreator) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *FakeTransferCreator) CreateArgsForCall(i int) api.TransferSpec {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return fake.createArgsForCall[i].arg1
}

var _ api.TransferCreator = new(FakeTransferCreator)
