// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/ice-stuff/clique/scheduler"
)

type FakeRandomIntGenerator struct {
	RandomStub        func(max int64) int64
	randomMutex       sync.RWMutex
	randomArgsForCall []struct {
		max int64
	}
	randomReturns struct {
		result1 int64
	}
}

func (fake *FakeRandomIntGenerator) Random(max int64) int64 {
	fake.randomMutex.Lock()
	fake.randomArgsForCall = append(fake.randomArgsForCall, struct {
		max int64
	}{max})
	fake.randomMutex.Unlock()
	if fake.RandomStub != nil {
		return fake.RandomStub(max)
	} else {
		return fake.randomReturns.result1
	}
}

func (fake *FakeRandomIntGenerator) RandomCallCount() int {
	fake.randomMutex.RLock()
	defer fake.randomMutex.RUnlock()
	return len(fake.randomArgsForCall)
}

func (fake *FakeRandomIntGenerator) RandomArgsForCall(i int) int64 {
	fake.randomMutex.RLock()
	defer fake.randomMutex.RUnlock()
	return fake.randomArgsForCall[i].max
}

func (fake *FakeRandomIntGenerator) RandomReturns(result1 int64) {
	fake.RandomStub = nil
	fake.randomReturns = struct {
		result1 int64
	}{result1}
}

var _ scheduler.RandomIntGenerator = new(FakeRandomIntGenerator)
