// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/glestaris/clique/dispatcher"
	"github.com/glestaris/clique/scheduler"
)

type FakeScheduler struct {
	ScheduleStub        func(task scheduler.Task)
	scheduleMutex       sync.RWMutex
	scheduleArgsForCall []struct {
		task scheduler.Task
	}
}

func (fake *FakeScheduler) Schedule(task scheduler.Task) {
	fake.scheduleMutex.Lock()
	fake.scheduleArgsForCall = append(fake.scheduleArgsForCall, struct {
		task scheduler.Task
	}{task})
	fake.scheduleMutex.Unlock()
	if fake.ScheduleStub != nil {
		fake.ScheduleStub(task)
	}
}

func (fake *FakeScheduler) ScheduleCallCount() int {
	fake.scheduleMutex.RLock()
	defer fake.scheduleMutex.RUnlock()
	return len(fake.scheduleArgsForCall)
}

func (fake *FakeScheduler) ScheduleArgsForCall(i int) scheduler.Task {
	fake.scheduleMutex.RLock()
	defer fake.scheduleMutex.RUnlock()
	return fake.scheduleArgsForCall[i].task
}

var _ dispatcher.Scheduler = new(FakeScheduler)
