// This file was generated by counterfeiter
package fakes

import (
	"net"
	"sync"

	"github.com/glestaris/ice-clique/api"
	"github.com/glestaris/ice-clique/dispatcher"
)

type FakeApiRegistry struct {
	RegisterStub        func(ip net.IP, res api.TransferResults)
	registerMutex       sync.RWMutex
	registerArgsForCall []struct {
		ip  net.IP
		res api.TransferResults
	}
}

func (fake *FakeApiRegistry) Register(ip net.IP, res api.TransferResults) {
	fake.registerMutex.Lock()
	fake.registerArgsForCall = append(fake.registerArgsForCall, struct {
		ip  net.IP
		res api.TransferResults
	}{ip, res})
	fake.registerMutex.Unlock()
	if fake.RegisterStub != nil {
		fake.RegisterStub(ip, res)
	}
}

func (fake *FakeApiRegistry) RegisterCallCount() int {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	return len(fake.registerArgsForCall)
}

func (fake *FakeApiRegistry) RegisterArgsForCall(i int) (net.IP, api.TransferResults) {
	fake.registerMutex.RLock()
	defer fake.registerMutex.RUnlock()
	return fake.registerArgsForCall[i].ip, fake.registerArgsForCall[i].res
}

var _ dispatcher.ApiRegistry = new(FakeApiRegistry)
